# Form implementation generated from reading ui file 'app/ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setObjectName("mainLayout")
        self.col_job = QtWidgets.QVBoxLayout()
        self.col_job.setSpacing(12)
        self.col_job.setObjectName("col_job")
        self.inputJobURL = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.inputJobURL.setObjectName("inputJobURL")
        self.col_job.addWidget(self.inputJobURL)
        self.jobButtons = QtWidgets.QHBoxLayout()
        self.jobButtons.setObjectName("jobButtons")
        self.btnFetchJob = QtWidgets.QPushButton(parent=self.centralWidget)
        self.btnFetchJob.setObjectName("btnFetchJob")
        self.jobButtons.addWidget(self.btnFetchJob)
        self.btnUseManualJob = QtWidgets.QPushButton(parent=self.centralWidget)
        self.btnUseManualJob.setObjectName("btnUseManualJob")
        self.jobButtons.addWidget(self.btnUseManualJob)
        self.col_job.addLayout(self.jobButtons)
        self.jobPreview = QtWidgets.QPlainTextEdit(parent=self.centralWidget)
        self.jobPreview.setObjectName("jobPreview")
        self.col_job.addWidget(self.jobPreview)
        self.settingsPanel = SettingsPanel(parent=self.centralWidget)
        self.settingsPanel.setObjectName("settingsPanel")
        self.col_job.addWidget(self.settingsPanel)
        self.mainLayout.addLayout(self.col_job)
        self.col_resume = QtWidgets.QVBoxLayout()
        self.col_resume.setSpacing(12)
        self.col_resume.setObjectName("col_resume")
        self.resumePicker = FilePicker(parent=self.centralWidget)
        self.resumePicker.setObjectName("resumePicker")
        self.col_resume.addWidget(self.resumePicker)
        self.resumePreview = QtWidgets.QPlainTextEdit(parent=self.centralWidget)
        self.resumePreview.setObjectName("resumePreview")
        self.col_resume.addWidget(self.resumePreview)
        self.btnTailor = QtWidgets.QPushButton(parent=self.centralWidget)
        self.btnTailor.setObjectName("btnTailor")
        self.col_resume.addWidget(self.btnTailor)
        self.mainLayout.addLayout(self.col_resume)
        self.col_output = QtWidgets.QVBoxLayout()
        self.col_output.setSpacing(12)
        self.col_output.setObjectName("col_output")
        self.outputPanel = OutputPanel(parent=self.centralWidget)
        self.outputPanel.setObjectName("outputPanel")
        self.col_output.addWidget(self.outputPanel)
        self.outputPreview = QtWidgets.QPlainTextEdit(parent=self.centralWidget)
        self.outputPreview.setObjectName("outputPreview")
        self.col_output.addWidget(self.outputPreview)
        self.exportButtons = QtWidgets.QHBoxLayout()
        self.exportButtons.setObjectName("exportButtons")
        self.btnExport = QtWidgets.QPushButton(parent=self.centralWidget)
        self.btnExport.setObjectName("btnExport")
        self.exportButtons.addWidget(self.btnExport)
        self.btnExportPDF = QtWidgets.QPushButton(parent=self.centralWidget)
        self.btnExportPDF.setObjectName("btnExportPDF")
        self.exportButtons.addWidget(self.btnExportPDF)
        self.col_output.addLayout(self.exportButtons)
        self.mainLayout.addLayout(self.col_output)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JobFit Pro"))
        self.inputJobURL.setPlaceholderText(_translate("MainWindow", "Paste job URL here…"))
        self.btnFetchJob.setText(_translate("MainWindow", "Fetch Job"))
        self.btnUseManualJob.setText(_translate("MainWindow", "Use Manual"))
        self.jobPreview.setPlaceholderText(_translate("MainWindow", "Fetched or manual job description will appear here…"))
        self.resumePreview.setPlaceholderText(_translate("MainWindow", "Resume text will appear here…"))
        self.btnTailor.setText(_translate("MainWindow", "Tailor Resume"))
        self.outputPreview.setPlaceholderText(_translate("MainWindow", "Tailored resume text will appear here…"))
        self.btnExport.setText(_translate("MainWindow", "Export DOCX"))
        self.btnExportPDF.setText(_translate("MainWindow", "Export PDF"))
from app.components.file_picker import FilePicker
from app.components.output_panel import OutputPanel
from app.components.settings_panel import SettingsPanel
