# core/processor/keyword_matcher.py
"""
Keyword extraction and overlap scoring.
Lightweight ATS-friendly keyword analyzer.
"""

import re
from collections import Counter

# Extended stopword list — covers common English words plus generic resume/job-posting
# filler that has no ATS signal value (colors, directions, vague nouns, etc.)
STOPWORDS = {
    # Articles / determiners
    "a",
    "an",
    "the",
    "this",
    "that",
    "these",
    "those",
    "some",
    "any",
    "each",
    "every",
    "both",
    "few",
    "more",
    "most",
    "other",
    "such",
    # Prepositions
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "up",
    "about",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "between",
    "out",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "per",
    "via",
    "vs",
    # Conjunctions
    "and",
    "or",
    "but",
    "nor",
    "so",
    "yet",
    "either",
    "neither",
    "not",
    "only",
    "whether",
    "while",
    "as",
    "if",
    "than",
    "until",
    "unless",
    "since",
    "when",
    "where",
    "which",
    "who",
    "whom",
    "whose",
    # Pronouns
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    # Auxiliary / linking verbs
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "shall",
    "should",
    "may",
    "might",
    "must",
    "can",
    "could",
    "need",
    "dare",
    "ought",
    # Common generic verbs (low signal for job keywords)
    "also",
    "just",
    "now",
    "how",
    "all",
    "well",
    "new",
    "use",
    "using",
    "used",
    "make",
    "made",
    "take",
    "taken",
    "get",
    "got",
    "give",
    "given",
    "work",
    "working",
    "works",
    "worked",
    "help",
    "helped",
    "helping",
    "helps",
    "set",
    "put",
    "keep",
    "let",
    "try",
    "tried",
    "call",
    "called",
    "ask",
    "feel",
    "seems",
    "become",
    "became",
    "include",
    "including",
    "provide",
    "provided",
    "providing",
    "ensure",
    "ensuring",
    "support",
    "able",
    "across",
    "based",
    "related",
    "within",
    "serve",
    "served",
    # Generic nouns with no job-specific signal
    "way",
    "ways",
    "role",
    "roles",
    "part",
    "parts",
    "time",
    "times",
    "year",
    "years",
    "day",
    "days",
    "week",
    "month",
    "place",
    "thing",
    "things",
    "area",
    "areas",
    "type",
    "types",
    "case",
    "cases",
    "point",
    "points",
    "fact",
    "line",
    "lines",
    "side",
    "end",
    "hand",
    "level",
    "levels",
    "term",
    "terms",
    "form",
    "forms",
    "life",
    "world",
    "group",
    "groups",
    "number",
    "numbers",
    "system",
    "systems",
    "order",
    "orders",
    "plan",
    "plans",
    "value",
    "values",
    "goal",
    "goals",
    "need",
    "needs",
    "result",
    "results",
    "impact",
    "impacts",
    "range",
    "ranges",
    "step",
    "steps",
    "stage",
    "stages",
    "process",
    "change",
    "various",
    "broad",
    "diverse",
    "general",
    "large",
    "small",
    "high",
    "low",
    "full",
    "open",
    "close",
    "next",
    "last",
    "good",
    "great",
    "strong",
    "key",
    "core",
    "main",
    "real",
    "long",
    "short",
    "right",
    "left",
    "own",
    "same",
    "different",
    # Geography / address words that appear in job postings but aren't skills
    "street",
    "avenue",
    "road",
    "drive",
    "suite",
    "floor",
    "office",
    "national",
    "local",
    "global",
    "remote",
    "hybrid",
    "onsite",
    # Career/posting filler
    "career",
    "careers",
    "job",
    "jobs",
    "opportunity",
    "opportunities",
    "position",
    "positions",
    "role",
    "candidate",
    "candidates",
    "intern",
    "interns",
    "internship",
    "internships",
    "together",
    "community",
    "forward",
    "contribute",
    "learn",
    "learning",
    "grow",
    "growing",
    "development",
    "training",
    "industry",
    "environment",
    "team",
    "teams",
    "company",
    "organization",
    "employer",
    # Numbers / misc
    "one",
    "two",
    "three",
    "four",
    "five",
    "first",
    "second",
    "third",
    "etc",
    "eg",
    "ie",
    "via",
    "inc",
    "llc",
    "ltd",
}

# Minimum keyword length — single chars and 2-char words are almost never ATS keywords
MIN_KW_LENGTH = 4

WORD_PATTERN = r"[A-Za-z][A-Za-z0-9\+\#\-]*[A-Za-z0-9]|[A-Za-z]{4,}"


def extract_keywords(text: str) -> Counter:
    """
    Extracts meaningful job keywords from text (skills, tools, tech stacks,
    domain terms). Excludes stopwords, punctuation tokens, and short filler.
    """
    words = re.findall(WORD_PATTERN, text.lower())
    filtered = [
        word
        for word in words
        if word not in STOPWORDS
        and len(word) >= MIN_KW_LENGTH
        and not re.fullmatch(r"[-\W]+", word)
    ]
    return Counter(filtered)


def keyword_overlap(job_text: str, resume_text: str) -> dict:
    """
    Returns keyword overlap + scoring metadata:
    - overlapping keywords with job frequencies
    - missing job keywords
    - match rate as a percentage
    """
    job_kw = extract_keywords(job_text)
    resume_kw = extract_keywords(resume_text)

    overlap = {word: job_kw[word] for word in job_kw if word in resume_kw}
    missing = {word: job_kw[word] for word in job_kw if word not in resume_kw}

    match_rate = (len(overlap) / max(len(job_kw), 1)) * 100

    return {
        "overlap": overlap,
        "missing": missing,
        "match_rate": round(match_rate, 2),
        "job_keyword_count": len(job_kw),
        "resume_keyword_count": len(resume_kw),
    }
